try:
	try:
		for i in rage:
			pass
	except Exception:
		print(1)

	for i in rage:
		pass
except Exception:
	print(2)
